### ISSUE TITLE
Can't download trained weights

### ISSUE THREAD

**Issue by HorusMaster** [dnalexen/ai_water_meter_reading#1]
Hi, Im trying to compare my results with yours, is it posible for you to send your trained weights.

Cheers

**Comment by akshayjaryal603** [comment]
Hi @HorusMaster, have you got the trained weight. Can you please share the trained weight or labelled data?

**Comment by dnalexen** [comment]
Hello this is the link of the trained weight: https://drive.google.com/file/d/14zTJdr4HZShyT_d8k9w8VGUS8RMA4nqL/view?usp=sharing.
This is the link of the labelled data: https://app.roboflow.com/ds/IoeDPeuY0z?key=BbnbigmG5a
