### ISSUE TITLE
incompatibility with python 3.7

### ISSUE THREAD

**Issue by savchoa** [dnalexen/ai_water_meter_reading#3]
when running nested notebook in google colab can't install numpy==1.22.0 specified in requirements.txt. This is caused by incompatibility with python 3.7 version. could you suggest how to solve this issue?

**Comment by dnalexen** [comment]
you can remove the version and just install numpy.

**Comment by savchoa** [comment]
Thanks. Another issue is (when loading weights from  https://drive.google.com/file/d/14zTJdr4HZShyT_d8k9w8VGUS8RMA4nqL/view?usp=sharing.): 

RuntimeError: Error(s) in loading state_dict for Yolov4:
	size mismatch for head.conv2.conv.0.weight: copying a param with shape torch.Size([51, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
	size mismatch for head.conv2.conv.0.bias: copying a param with shape torch.Size([51]) from checkpoint, the shape in current model is torch.Size([18]).

could you suggest what i am doing wrong? perhaps the classes parameter should be set to something other than 1. I just want to use your weights to recognize the individual digits of the counter. Thanks

**Comment by dnalexen** [comment]
The yolo v4 code source has been updated. There are some changes that make this notebook obsolete. I suggest that you use a new code source from this roboflow page: https://models.roboflow.com/.
